// src/app/shared/data.service.ts
import { Injectable } from '@angular/core';
import { Unit, Upgrade } from './models';

@Injectable({ providedIn: 'root' })
export class DataService {
  readonly UNIDADES_DB: Unit[] = [
    {
      id: 'GZ01',
      nombre: 'Goku',
      subtitulo: 'Saiyan criado en la tierra',
      faccion: 'Guerreros Z',
      categoria: 'Comandante (P)',
      coste: 150,
      heridas: 5,
      entereza: 3,
      velocidad: 2,
      defensa: 'blanco',
      barraDeMejoras: ['Mando', 'Entrenamiento', 'Fuerza'],
      cualidades: [
        'Desvío',
        'Vuelo 2',
        'Corazón de Héroe',
        'Kaioken',
        'Zenkai',
        'Ráfaga de Ki Mejorada',
      ],
    },
    {
      id: 'GZ02',
      nombre: 'Piccolo',
      subtitulo: 'Estratega Namekiano',
      faccion: 'Guerreros Z',
      categoria: 'Agente (O)',
      coste: 125,
      heridas: 5,
      entereza: 2,
      velocidad: 2,
      defensa: 'rojo',
      barraDeMejoras: ['Entrenamiento', 'Fuerza'],
      cualidades: [
        'Guardián 2: Gohan',
        'Líder Sustituto',
        'Regeneración 1',
        'Vuelo 2',
        'Tutor',
        'Ráfaga de Ki Mejorada',
      ],
    },
    {
      id: 'GZ03',
      nombre: 'Gohan',
      subtitulo: 'Niño con Potencial Oculto',
      faccion: 'Guerreros Z',
      categoria: 'Agente (O)',
      coste: 50,
      heridas: 3,
      entereza: 1,
      velocidad: 2,
      defensa: 'blanco',
      barraDeMejoras: ['Entrenamiento'],
      cualidades: [
        'Poder Oculto',
        'Ira Incontrolada',
        'Desapercebido',
        'Vuelo 1',
        'Cola',
        'Ráfaga de Ki',
      ],
    },
    {
      id: 'GZ04',
      nombre: 'Krilin',
      subtitulo: 'el Terrícola más Fuerte',
      faccion: 'Guerreros Z',
      categoria: 'Agente (O)',
      coste: 75,
      heridas: 4,
      entereza: 2,
      velocidad: 2,
      defensa: 'blanco',
      barraDeMejoras: ['Entrenamiento', 'Equipo'],
      cualidades: ['¡Taiyoken!', 'Trabajo en Equipo: Goku', 'Vuelo 1', 'Ráfaga de Ki'],
    },
    {
      id: 'GZ05',
      nombre: 'Tenshinhan',
      subtitulo: 'Maestro de la Escuela Grulla',
      faccion: 'Guerreros Z',
      categoria: 'Agente (O)',
      coste: 90,
      heridas: 4,
      entereza: 2,
      velocidad: 2,
      defensa: 'blanco',
      barraDeMejoras: ['Entrenamiento', 'Fuerza'],
      cualidades: [
        'Contrapartida: Chaoz',
        'Vuelo 1',
        'Telequinesis',
        'Sacrificio Heroico',
        'Ráfaga de Ki',
      ],
    },
    {
      id: 'GZ06',
      nombre: 'Yamcha',
      subtitulo: 'Lobo Solitario',
      faccion: 'Guerreros Z',
      categoria: 'Agente (O)',
      coste: 65,
      heridas: 4,
      entereza: 1,
      velocidad: 2,
      defensa: 'blanco',
      barraDeMejoras: ['Entrenamiento', 'Equipo'],
      cualidades: [
        'Acometida',
        'Vuelo 1',
        'Trabajo en Equipo: Krilin',
        'Exceso de Confianza',
        'Ráfaga de Ki',
      ],
    },
    {
      id: 'GZ07',
      nombre: 'Nail',
      subtitulo: 'Defensor de Namek',
      faccion: 'Guerreros Z',
      categoria: 'Agente (O)',
      coste: 95,
      heridas: 5,
      entereza: 2,
      velocidad: 2,
      defensa: 'rojo',
      barraDeMejoras: ['Entrenamiento', 'Fuerza'],
      cualidades: [
        'Asimilación Namekiana',
        'Regeneración 1',
        'Vuelo 1',
        'Guardián 1: Dende',
        'Ráfaga de Ki Mejorada',
      ],
    },
    {
      id: 'GZ08',
      nombre: 'Dende',
      subtitulo: 'Joven Sanador',
      faccion: 'Guerreros Z',
      categoria: 'Apoyo (R)',
      coste: 35,
      heridas: 3,
      entereza: 1,
      velocidad: 2,
      defensa: 'blanco',
      barraDeMejoras: ['Equipo'],
      cualidades: ['Curación Namekiana', 'No combatiente', 'Desapercebido', 'Vuelo 1'],
    },
    {
      id: 'GZ09',
      nombre: 'Yajirobe',
      subtitulo: 'Samurai Errante',
      faccion: 'Guerreros Z',
      categoria: 'Agente (O)',
      coste: 65,
      heridas: 4,
      entereza: 1,
      velocidad: 2,
      defensa: 'blanco',
      barraDeMejoras: ['Equipo'],
      cualidades: ['¡Semillas Senzu!', 'Desapercebido'],
    },
    {
      id: 'GZ10',
      nombre: 'Bulma',
      subtitulo: 'Genio de Capsule Corp. (Saga de Namek)',
      faccion: 'Guerreros Z',
      categoria: 'Apoyo (R)',
      coste: 45,
      heridas: 3,
      entereza: 1,
      velocidad: 2,
      defensa: 'blanco',
      barraDeMejoras: ['Equipo', 'Equipo'],
      cualidades: ['No combatiente', 'Radar Dragón', 'Ingenio de Capsule Corp.', 'Desapercebido'],
    },
    {
      id: 'GZ11',
      nombre: 'Gohan del Futuro',
      subtitulo: 'Mentor Desesperado',
      faccion: 'Guerreros Z',
      categoria: 'Agente (O)',
      coste: 155,
      heridas: 4,
      entereza: 3,
      velocidad: 2,
      defensa: 'blanco',
      barraDeMejoras: ['Entrenamiento', 'Fuerza'],
      cualidades: [
        'Contrapartida: Trunks del Futuro',
        'Legado del Futuro',
        'Paradoja Temporal',
        'Corazón de Héroe',
        'Zenkai',
        'Vuelo 1',
        'Ráfaga de Ki Mejorada',
      ],
    },
    {
      id: 'SY01',
      nombre: 'Vegeta',
      subtitulo: 'Príncipe de los Saiyan',
      faccion: 'Guerreros Saiyan',
      categoria: 'Comandante (P)',
      coste: 160,
      heridas: 5,
      entereza: 3,
      velocidad: 2,
      defensa: 'rojo',
      barraDeMejoras: ['Mando', 'Entrenamiento', 'Fuerza'],
      cualidades: [
        'Tirador de primera',
        'Liderazgo Despiadado',
        'Zenkai',
        'Vuelo 2',
        'Cola',
        'Ráfaga de Ki Mejorada',
      ],
    },
    {
      id: 'SY02',
      nombre: 'Raditz',
      subtitulo: 'Hermano de Kakarotto',
      faccion: 'Guerreros Saiyan',
      categoria: 'Agente (O)',
      coste: 85,
      heridas: 4,
      entereza: 2,
      velocidad: 2,
      defensa: 'rojo',
      barraDeMejoras: ['Entrenamiento', 'Equipo'],
      cualidades: [
        'Aprovechar Debilidad',
        'Zenkai',
        'Vuelo 1',
        'Cazador: Goku',
        'Cola',
        'Ráfaga de Ki',
      ],
    },
    {
      id: 'SY03',
      nombre: 'Nappa',
      subtitulo: 'Conquistador Saiyan',
      faccion: 'Guerreros Saiyan',
      categoria: 'Pesada (Q)',
      coste: 110,
      heridas: 6,
      entereza: 2,
      velocidad: 2,
      defensa: 'rojo',
      barraDeMejoras: ['Entrenamiento', 'Equipo'],
      cualidades: ['Acometida', 'Brutalidad Saiyan', 'Zenkai', 'Cola', 'Vuelo 1', 'Ráfaga de Ki'],
    },
    {
      id: 'SY04',
      nombre: 'Bardock',
      subtitulo: 'Padre de Kakarot',
      faccion: 'Guerreros Saiyan',
      categoria: 'Fuerzas Especiales (N)',
      coste: 115,
      heridas: 5,
      entereza: 3,
      velocidad: 2,
      defensa: 'rojo',
      barraDeMejoras: ['Mando', 'Entrenamiento', 'Fuerza'],
      cualidades: [
        'Visión del Futuro',
        'Zenkai',
        'Vuelo 2',
        'Equipo Bardock',
        'Líder de Escuadrón Legendario',
        'Cola',
        'Ráfaga de Ki Mejorada',
      ],
    },
    {
      id: 'SY05',
      nombre: 'Tora',
      subtitulo: 'Segundo al Mando',
      faccion: 'Guerreros Saiyan',
      categoria: 'Fuerzas Especiales (N)',
      coste: 90,
      heridas: 5,
      entereza: 2,
      velocidad: 2,
      defensa: 'rojo',
      barraDeMejoras: ['Entrenamiento', 'Equipo'],
      cualidades: [
        'Equipo Bardock',
        'Trabajo en Equipo: Bardock',
        'Zenkai',
        'Vuelo 2',
        'Cola',
        'Ráfaga de Ki',
      ],
    },
    {
      id: 'SY06',
      nombre: 'Fasha',
      subtitulo: 'Guerrera Ágil',
      faccion: 'Guerreros Saiyan',
      categoria: 'Fuerzas Especiales (N)',
      coste: 75,
      heridas: 4,
      entereza: 2,
      velocidad: 2,
      defensa: 'blanco',
      barraDeMejoras: ['Entrenamiento', 'Equipo'],
      cualidades: [
        'Equipo Bardock',
        'Tirador de primera',
        'Zenkai',
        'Vuelo 2',
        'Cola',
        'Ráfaga de Ki',
      ],
    },
    {
      id: 'SY07',
      nombre: 'Borgos',
      subtitulo: 'Bruto del Grupo',
      faccion: 'Guerreros Saiyan',
      categoria: 'Fuerzas Especiales (N)',
      coste: 95,
      heridas: 6,
      entereza: 2,
      velocidad: 2,
      defensa: 'rojo',
      barraDeMejoras: ['Entrenamiento', 'Equipo'],
      cualidades: [
        'Equipo Bardock',
        'Acometida',
        'Brutalidad Saiyan',
        'Zenkai',
        'Vuelo 1',
        'Cola',
        'Ráfaga de Ki',
      ],
    },
    {
      id: 'SY08',
      nombre: 'Shugesh',
      subtitulo: 'Tanque del Escuadrón',
      faccion: 'Guerreros Saiyan',
      categoria: 'Fuerzas Especiales (N)',
      coste: 85,
      heridas: 6,
      entereza: 2,
      velocidad: 2,
      defensa: 'rojo',
      barraDeMejoras: ['Entrenamiento', 'Equipo'],
      cualidades: [
        'Equipo Bardock',
        'Guardián 1: Bardock',
        '¡Soy Indestructible!',
        'Zenkai',
        'Vuelo 1',
        'Cola',
        'Ráfaga de Ki',
      ],
    },
    {
      id: 'SY09',
      nombre: 'Turles',
      subtitulo: 'Pirata Espacial Saiyan',
      faccion: 'Guerreros Saiyan',
      categoria: 'Agente (O)',
      coste: 100,
      heridas: 5,
      entereza: 2,
      velocidad: 2,
      defensa: 'rojo',
      barraDeMejoras: ['Entrenamiento', 'Equipo'],
      cualidades: ['Vuelo 1', 'Zenkai', 'Cola', 'Ráfaga de Ki', 'Liderazgo Despiadado'],
    },
    {
      id: 'SY10',
      nombre: 'Saibaman',
      subtitulo: '',
      faccion: 'Guerreros Saiyan',
      categoria: 'Tropa (M)',
      coste: 15,
      heridas: 1,
      entereza: 1,
      velocidad: 2,
      defensa: 'blanco',
      barraDeMejoras: [],
      cualidades: ['Autodestrucción 1'],
    },
    {
      id: 'SY11',
      nombre: 'Broly',
      subtitulo: 'Saiyan Exiliado',
      faccion: 'Guerreros Saiyan',
      categoria: 'Pesada (Q)',
      coste: 115,
      heridas: 3,
      entereza: 3,
      velocidad: 2,
      defensa: 'rojo',
      barraDeMejoras: ['Entrenamiento', 'Fuerza'],
      cualidades: [
        'Poder Legendario',
        'Furia Latente',
        'Zenkai',
        'Vuelo 1',
        'Cola',
        'Ráfaga de Ki',
      ],
    },
    {
      id: 'SY12',
      nombre: 'Paragus',
      subtitulo: 'Padre Vengativo',
      faccion: 'Guerreros Saiyan',
      categoria: 'Agente (O)',
      coste: 65,
      heridas: 4,
      entereza: 1,
      velocidad: 2,
      defensa: 'blanco',
      barraDeMejoras: [],
      cualidades: ['Control Remoto: Broly', 'Cobarde', 'Observador 1', 'Vuelo 1', 'Ráfaga de Ki'],
    },
    {
      id: 'SY13',
      nombre: 'Rey Vegeta',
      subtitulo: 'Soberano Orgulloso',
      faccion: 'Guerreros Saiyan',
      categoria: 'Comandante (P)',
      coste: 140,
      heridas: 5,
      entereza: 3,
      velocidad: 2,
      defensa: 'rojo',
      barraDeMejoras: ['Mando', 'Entrenamiento', 'Fuerza'],
      cualidades: [
        'Rey de los Saiyans',
        'Autoridad Real: Príncipe Vegeta',
        'Liderazgo Despiadado',
        'Zenkai',
        'Vuelo 2',
        'Cola',
        'Ráfaga de Ki Mejorada',
      ],
    },
    {
      id: 'EF01',
      nombre: 'Freezer',
      subtitulo: 'Tirano Galáctico (Primera Forma)',
      faccion: 'Ejército de Freezer',
      categoria: 'Comandante (P)',
      coste: 170,
      heridas: 6,
      entereza: 3,
      velocidad: 2,
      defensa: 'rojo',
      barraDeMejoras: ['Mando', 'Entrenamiento', 'Fuerza'],
      cualidades: [
        'Vuelo 2',
        'Ráfaga de Ki Mejorada',
        'Tirador de primera 1',
        'Miedo Tiránico',
        'Tirano Despiadado',
      ],
    },
    {
      id: 'EF02',
      nombre: 'Rey Cold',
      subtitulo: 'Patriarca del Imperio',
      faccion: 'Ejército de Freezer',
      categoria: 'Comandante (P)',
      coste: 160,
      heridas: 7,
      entereza: 2,
      velocidad: 2,
      defensa: 'rojo',
      barraDeMejoras: ['Mando', 'Entrenamiento'],
      cualidades: [
        'Autoridad Imperial',
        'Autoridad Paterna: Freezer',
        'Ráfaga de Ki Mejorada',
        'Vuelo 1',
        'Guardaespaldas Imperial',
        'Objetivo Masivo',
      ],
    },
    {
      id: 'EF03',
      nombre: 'Zarbon',
      subtitulo: 'General de Élite',
      faccion: 'Ejército de Freezer',
      categoria: 'Agente (O)',
      coste: 70,
      heridas: 4,
      entereza: 2,
      velocidad: 2,
      defensa: 'blanco',
      barraDeMejoras: ['Equipo', 'Entrenamiento'],
      cualidades: ['Vuelo 1', 'Ráfaga de Ki', 'Transformación Monstruosa'],
    },
    {
      id: 'EF04',
      nombre: 'Dodoria',
      subtitulo: 'Guardaespaldas Brutal',
      faccion: 'Ejército de Freezer',
      categoria: 'Agente (O)',
      coste: 70,
      heridas: 5,
      entereza: 2,
      velocidad: 2,
      defensa: 'rojo',
      barraDeMejoras: ['Equipo', 'Entrenamiento'],
      cualidades: ['Acometida', 'Guardián 1: Freezer', 'Vuelo 1', 'Ráfaga de Ki'],
    },
    {
      id: 'EF05',
      nombre: 'Kiwi (Cui)',
      subtitulo: 'Rival de Vegeta',
      faccion: 'Ejército de Freezer',
      categoria: 'Agente (O)',
      coste: 55,
      heridas: 4,
      entereza: 1,
      velocidad: 2,
      defensa: 'blanco',
      barraDeMejoras: ['Equipo'],
      cualidades: ['Vuelo 1', 'Ráfaga de Ki', 'Tirador de primera 1', 'Cazador: Vegeta'],
    },
    {
      id: 'EF06',
      nombre: 'Capitán Ginyu',
      subtitulo: 'Líder de las Fuerzas Especiales',
      faccion: 'Ejército de Freezer',
      categoria: 'Agente (O)',
      coste: 120,
      heridas: 5,
      entereza: 3,
      velocidad: 2,
      defensa: 'rojo',
      barraDeMejoras: ['Mando', 'Entrenamiento', 'Fuerza'],
      cualidades: [
        'Ráfaga de Ki Mejorada',
        'Vuelo 2',
        'Cambio de Cuerpo',
        'Fuerza Ginyu',
        'Comando de las Fuerzas Ginyu',
      ],
    },
    {
      id: 'EF07',
      nombre: 'Burter',
      subtitulo: 'El Cometa Azul',
      faccion: 'Ejército de Freezer',
      categoria: 'Fuerzas Especiales (N)',
      coste: 75,
      heridas: 4,
      entereza: 2,
      velocidad: 3,
      defensa: 'blanco',
      barraDeMejoras: ['Equipo', 'Entrenamiento'],
      cualidades: [
        'Vuelo 1',
        'Ráfaga de Ki',
        'Tirador de primera 1',
        'Fuerza Ginyu',
        'Ataque Combinado: Jeice',
      ],
    },
    {
      id: 'EF08',
      nombre: 'Jeice',
      subtitulo: 'El Cometa Rojo',
      faccion: 'Ejército de Freezer',
      categoria: 'Fuerzas Especiales (N)',
      coste: 70,
      heridas: 4,
      entereza: 2,
      velocidad: 2,
      defensa: 'blanco',
      barraDeMejoras: ['Equipo', 'Entrenamiento'],
      cualidades: [
        'Vuelo 1',
        'Ráfaga de Ki',
        'Tirador de primera 1',
        'Fuerza Ginyu',
        'Ataque Combinado: Burter',
      ],
    },
    {
      id: 'EF09',
      nombre: 'Recoome',
      subtitulo: 'El Demoledor',
      faccion: 'Ejército de Freezer',
      categoria: 'Fuerzas Especiales (N)',
      coste: 85,
      heridas: 6,
      entereza: 2,
      velocidad: 2,
      defensa: 'rojo',
      barraDeMejoras: ['Equipo', 'Entrenamiento'],
      cualidades: ['Vuelo 1', 'Ráfaga de Ki', 'Acometida', 'Fuerza Ginyu', '¡Soy Indestructible!'],
    },
    {
      id: 'EF10',
      nombre: 'Guldo',
      subtitulo: 'Maestro del Control Temporal',
      faccion: 'Ejército de Freezer',
      categoria: 'Fuerzas Especiales (N)',
      coste: 60,
      heridas: 3,
      entereza: 1,
      velocidad: 1,
      defensa: 'blanco',
      barraDeMejoras: ['Equipo', 'Entrenamiento'],
      cualidades: ['Fuerza Ginyu', 'Telequinesis', '¡Congelación del tiempo!', 'Cobarde'],
    },
    {
      id: 'EF11',
      nombre: 'Appule',
      subtitulo: 'Soldado de Freezer',
      faccion: 'Ejército de Freezer',
      categoria: 'Tropa (M)',
      coste: 25,
      heridas: 3,
      entereza: 1,
      velocidad: 2,
      defensa: 'blanco',
      barraDeMejoras: ['Equipo'],
      cualidades: ['Vuelo 1', 'Disciplina del Ejército'],
    },
    {
      id: 'AN01',
      nombre: 'Dr. Gero',
      subtitulo: 'Creador Vengativo (Androide 20)',
      faccion: 'Androides',
      categoria: 'Comandante (P)',
      coste: 145,
      heridas: 5,
      entereza: 2,
      velocidad: 2,
      defensa: 'blanco',
      barraDeMejoras: ['Mando', 'Entrenamiento', 'Equipo'],
      cualidades: ['Absorción de Energía', 'Observador 2', 'Análisis de Combate', 'Vuelo 1'],
    },
    {
      id: 'AN02',
      nombre: 'Cell',
      subtitulo: 'Ser Perfecto (Forma Perfecta)',
      faccion: 'Androides',
      categoria: 'Comandante (P)',
      coste: 185,
      heridas: 8,
      entereza: 3,
      velocidad: 2,
      defensa: 'rojo',
      barraDeMejoras: ['Mando', 'Entrenamiento', 'Fuerza'],
      cualidades: [
        'Anfitrión del Juego de Cell',
        'Nacimiento de los Cell Jr.',
        'Regeneración 1',
        'Zenkai',
        'Vuelo 2',
        'Ráfaga de Ki Mejorada',
      ],
    },
    {
      id: 'AN03',
      nombre: 'Androide 13',
      subtitulo: 'Líder de la Venganza',
      faccion: 'Androides',
      categoria: 'Agente (O)',
      coste: 105,
      heridas: 5,
      entereza: 3,
      velocidad: 2,
      defensa: 'rojo',
      barraDeMejoras: ['Entrenamiento', 'Equipo', 'Fuerza'],
      cualidades: [
        'Fusión de Supercomputadora',
        'Trío Androide',
        'Líder del Grupo',
        'Energía Infinita (Fiable 1)',
        'Vuelo 1',
      ],
    },
    {
      id: 'AN04',
      nombre: 'Androide 17',
      subtitulo: 'Amenaza Implacable',
      faccion: 'Androides',
      categoria: 'Agente (O)',
      coste: 95,
      heridas: 5,
      entereza: 2,
      velocidad: 2,
      defensa: 'rojo',
      barraDeMejoras: ['Entrenamiento', 'Equipo'],
      cualidades: [
        'Ataque Combinado: Androide 18',
        'Energía Infinita (Fiable 1)',
        'Barrera Androide',
        'Vuelo 1',
        'Ráfaga de Ki',
      ],
    },
    {
      id: 'AN05',
      nombre: 'Androide 18',
      subtitulo: 'Belleza Letal',
      faccion: 'Androides',
      categoria: 'Agente (O)',
      coste: 90,
      heridas: 4,
      entereza: 2,
      velocidad: 2,
      defensa: 'rojo',
      barraDeMejoras: ['Entrenamiento', 'Equipo'],
      cualidades: [
        'Ataque Combinado: Androide 17',
        'Energía Infinita (Fiable 1)',
        'Juego Cruel',
        'Vuelo 1',
        'Ráfaga de Ki',
      ],
    },
    {
      id: 'AN06',
      nombre: 'Androide 16',
      subtitulo: 'Guardián Silencioso',
      faccion: 'Androides',
      categoria: 'Pesada (Q)',
      coste: 125,
      heridas: 7,
      entereza: 3,
      velocidad: 2,
      defensa: 'rojo',
      barraDeMejoras: ['Entrenamiento', 'Equipo'],
      cualidades: [
        'Guardián 2: Androide 18',
        'Cazador: Goku',
        'Autodestrucción 3: Sacrificio Final',
        'Vuelo 1',
      ],
    },
    {
      id: 'AN07',
      nombre: 'Cell (Primera Forma)',
      subtitulo: 'Cazador Silencioso',
      faccion: 'Androides',
      categoria: 'Pesada (Q)',
      coste: 135,
      heridas: 6,
      entereza: 3,
      velocidad: 2,
      defensa: 'rojo',
      barraDeMejoras: ['Entrenamiento', 'Equipo'],
      cualidades: ['Regeneración 1', 'Zenkai', 'Vuelo 1', 'Ráfaga de Ki'],
    },
    {
      id: 'AN08',
      nombre: 'Cell (Segunda Forma)',
      subtitulo: 'Engreído y Poderoso',
      faccion: 'Androides',
      categoria: 'Pesada (Q)',
      coste: 150,
      heridas: 7,
      entereza: 3,
      velocidad: 2,
      defensa: 'rojo',
      barraDeMejoras: ['Entrenamiento', 'Fuerza'],
      cualidades: [
        'Obsesión: Perfección (Androide 18)',
        'Regeneración 1',
        'Zenkai',
        'Brutalidad Saiyan',
        'Vuelo 1',
        'Ráfaga de Ki Mejorada',
      ],
    },
    {
      id: 'AN09',
      nombre: 'Androide 14',
      subtitulo: 'Gigante Implacable',
      faccion: 'Androides',
      categoria: 'Fuerzas Especiales (N)',
      coste: 80,
      heridas: 6,
      entereza: 2,
      velocidad: 2,
      defensa: 'rojo',
      barraDeMejoras: ['Entrenamiento', 'Equipo'],
      cualidades: ['Acometida', 'Trío Androide', 'Energía Infinita (Fiable 1)', 'Vuelo 1'],
    },
    {
      id: 'AN10',
      nombre: 'Androide 15',
      subtitulo: 'Asesino Frío',
      faccion: 'Androides',
      categoria: 'Fuerzas Especiales (N)',
      coste: 75,
      heridas: 5,
      entereza: 2,
      velocidad: 2,
      defensa: 'rojo',
      barraDeMejoras: ['Entrenamiento', 'Equipo'],
      cualidades: ['Análisis de Datos', 'Trío Androide', 'Energía Infinita (Fiable 1)', 'Vuelo 1'],
    },
    {
      id: 'AN11',
      nombre: 'Androide 19',
      subtitulo: 'Marioneta Leal',
      faccion: 'Androides',
      categoria: 'Tropa (M)',
      coste: 55,
      heridas: 4,
      entereza: 2,
      velocidad: 2,
      defensa: 'blanco',
      barraDeMejoras: ['Entrenamiento', 'Equipo'],
      cualidades: ['Absorción de Energía', 'Guardián 1: Dr. Gero', 'Vuelo 1'],
    },
    {
      id: 'AN12',
      nombre: 'Cell Jr.',
      subtitulo: 'Progenie del Terror',
      faccion: 'Androides',
      categoria: 'Tropa (M)',
      coste: 45,
      heridas: 4,
      entereza: 1,
      velocidad: 2,
      defensa: 'blanco',
      barraDeMejoras: [],
      cualidades: ['Progenie de Cell', 'Juego Cruel', 'Regeneración 1', 'Zenkai', 'Vuelo 1'],
    },
    {
      id: 'AN13',
      nombre: 'Androide 21',
      subtitulo: 'Científica Brillante',
      faccion: 'Androides',
      categoria: 'Apoyo (R)',
      coste: 85,
      heridas: 4,
      entereza: 2,
      velocidad: 2,
      defensa: 'blanco',
      barraDeMejoras: ['Mando', 'Entrenamiento'],
      cualidades: ['Mejora de Campo', 'Genio Científico', 'No combatiente', 'Vuelo 1'],
    },
  ];
  readonly MEJORAS_DB: Upgrade[] = [
    {
      id: 'ME01',
      nombre: 'Tenacidad',
      tipo: 'Entrenamiento',
      coste: 5,
      restriccion: 'Ninguna',
      descripcion: 'Ganas Entereza +1.',
    },
    {
      id: 'ME02',
      nombre: 'Voluntad de Lucha',
      tipo: 'Entrenamiento',
      coste: 5,
      restriccion: 'Ninguna',
      descripcion:
        'Mientras te encuentres en el estado "Al Límite", puedes volver a tirar un dado durante tu "Tirada de Resistencia".',
    },
    {
      id: 'ME03',
      nombre: 'Preparación Física',
      tipo: 'Entrenamiento',
      coste: 10,
      restriccion: 'Ninguna',
      descripcion: 'Ganas +1 a tu Umbral de Heridas.',
    },
    {
      id: 'ME04',
      nombre: 'Entrenamiento del Maestro Roshi',
      tipo: 'Entrenamiento',
      coste: 8,
      restriccion: 'Solo Goku',
      descripcion:
        'Agotar (L). Al final de tu activación, si te encuentras en el estado "Al Límite", puedes agotar esta carta para quitarte 1 ficha de "Fatiga".',
    },
    {
      id: 'ME05',
      nombre: 'Meditación Namekiana',
      tipo: 'Entrenamiento',
      coste: 10,
      restriccion: 'Solo Piccolo',
      descripcion:
        'Acción de carta (I). Elige y prepara 1 de tus cartas de mejora agotadas o una de tus armas con la cualidad Agostar L.',
    },
    {
      id: 'ME06',
      nombre: 'Entrenamiento de Gravedad Intensa',
      tipo: 'Entrenamiento',
      coste: 10,
      restriccion: 'Solo Vegeta',
      descripcion:
        'Acción de carta (I). Sufre 1 herida para preparar 1 de tus cartas de mejora agotadas o una de tus armas con la cualidad Agostar L.',
    },
    {
      id: 'ME07',
      nombre: 'Supervivencia del Emperador',
      tipo: 'Entrenamiento',
      coste: 12,
      restriccion: 'Solo Freezer',
      descripcion:
        'La primera vez que entres en el estado "Al Límite" en cada partida, ganas la cualidad Regeneración 2 hasta el final de la partida.',
    },
    {
      id: 'ME08',
      nombre: 'Maestría del Kienzan',
      tipo: 'Entrenamiento',
      coste: 8,
      restriccion: 'Solo Krilin',
      descripcion: 'Tu arma Kienzan pierde la cualidad Lento y Constante.',
    },
    {
      id: 'ME09',
      nombre: 'La Última Batalla',
      tipo: 'Entrenamiento',
      coste: 10,
      restriccion: 'Solo Bardock',
      descripcion:
        'Mientras seas la única unidad aliada en el campo de batalla con la cualidad Equipo Bardock, tus armas ganan Perforante 1.',
    },
    {
      id: 'ME10',
      nombre: 'Fruta del Árbol del Poder',
      tipo: 'Entrenamiento',
      coste: 15,
      restriccion: 'Solo Turles',
      descripcion:
        'Agostar (L). Acción de carta (I). Quítate hasta 2 fichas de Herida. Hasta el final de la ronda, tus armas ganan Perforante 1 e Impacto 1.',
    },
    {
      id: 'ME11',
      nombre: 'Juego Macabro',
      tipo: 'Entrenamiento',
      coste: 8,
      restriccion: 'Solo Androide 17 o Androide 18',
      descripcion:
        'Cuando te actives, si la otra unidad "melliza" (Androide 18 o Androide 17, respectivamente) está a alcance 1-2, puedes realizar una acción de movimiento de Velocidad 1 gratuita.',
    },
    {
      id: 'ME12',
      nombre: 'Transmisión Instantánea Saiyan',
      tipo: 'Entrenamiento',
      coste: 20,
      restriccion: 'Solo Cell',
      descripcion:
        'Una vez por partida. Agotar (L). Acción de carta (II). Puedes retirar tu miniatura del campo de batalla y colocarla en contacto peana con peana con cualquier otra miniatura (aliada o enemiga) en el campo de batalla.',
    },
    {
      id: 'ME13',
      nombre: 'Rastreador (Scouter)',
      tipo: 'Equipo',
      coste: 5,
      restriccion: 'Saiyan, Ejército de Freezer',
      descripcion: 'Ganas la cualidad Observador 1.',
    },
    {
      id: 'ME14',
      nombre: 'Dispositivo de rastreo de Capsule Corp.',
      tipo: 'Equipo',
      coste: 5,
      restriccion: 'Guerreros Z',
      descripcion: 'Ganas la cualidad Observador 1.',
    },
    {
      id: 'ME15',
      nombre: 'Armadura de Combate',
      tipo: 'Equipo',
      coste: 10,
      restriccion: 'Saiyan, Ejército de Freezer, Krilin y Gohan',
      descripcion:
        'Mientras te defiendes, si tu dado de defensa nativo es blanco, puedes tratarlo como si fuera rojo.',
    },
    {
      id: 'ME16',
      nombre: 'Ropa Pesada',
      tipo: 'Equipo',
      coste: 10,
      restriccion: 'Guerreros Z',
      descripcion:
        'Agotar (L). Al inicio de tu activación, puedes agotar esta carta para ganar Velocidad -1 para esta activación. Si lo haces, al final de tu activación, ganas 1 ficha de Esquiva y preparas esta carta.',
    },
    {
      id: 'ME17',
      nombre: 'Nube Kinton',
      tipo: 'Equipo',
      coste: 15,
      restriccion: 'Solo Goku',
      descripcion:
        'Acción de carta (I). Realiza un movimiento de Velocidad 3. Durante este movimiento, ignoras el terreno y las miniaturas.',
    },
    {
      id: 'ME18',
      nombre: 'Semillas de Saibaman',
      tipo: 'Equipo',
      coste: 20,
      restriccion: 'Solo Nappa',
      descripcion:
        'Debes incluir al menos una unidad de Saibaman en tu ejército para equipar esta mejora. Acción de carta (II). Despliega una unidad de Saibaman de tu ejército que no haya sido desplegada. Coloca la miniatura de esa unidad en contacto peana con peana contigo. Esta mejora no puede ser usada si todas tus unidades de Saibaman ya están en el campo de batalla o han sido derrotadas.',
    },
    {
      id: 'ME19',
      nombre: 'Protocolos de Autorreparación',
      tipo: 'Equipo',
      coste: 10,
      restriccion: 'Solo Androide',
      descripcion:
        'Agotar (L). Acción de carta (I). Tira 1 dado de defensa rojo. Por cada resultado de bloqueo (D) o incremento (E) que obtengas, quítate 1 ficha de Herida.',
    },
    {
      id: 'ME20',
      nombre: 'Líder Inspirador',
      tipo: 'Mando',
      coste: 15,
      restriccion: 'Solo Comandante (P)',
      descripcion:
        'Agostar (L). Acción de carta (I). Elige una unidad aliada a alcance 1-3. Esa unidad puede elegir uno de los siguientes beneficios:\n• Supera automáticamente su próxima Tirada de Resistencia en esta ronda.\n• Quitarse 1 ficha de Inmovilización.',
    },
    {
      id: 'ME21',
      nombre: 'Coordinación Táctica',
      tipo: 'Mando',
      coste: 8,
      restriccion: 'Ninguna',
      descripcion:
        'Acción de carta (I). Elige otra unidad aliada a alcance 1-2. Esa unidad gana 1 ficha de Ataque apuntado o 1 ficha de Esquiva.',
    },
    {
      id: 'ME22',
      nombre: 'Furia del Príncipe',
      tipo: 'Mando',
      coste: 18,
      restriccion: 'Solo Vegeta',
      descripcion:
        'Agotar (L). Cuando otra unidad Saiyan aliada a alcance 1-3 sea derrotada, después de que se resuelva el ataque, puedes agotar esta carta para que Vegeta gane inmediatamente 1 ficha de Ataque apuntado y realice una acción de movimiento gratuita.',
    },
    {
      id: 'ME23',
      nombre: 'No eres más que una herramienta',
      tipo: 'Mando',
      coste: 5,
      restriccion: 'Solo Freezer',
      descripcion:
        'Acción de carta (I). Derrota a una unidad aliada de Tropa (M) o Fuerzas Especiales (N) a alcance 1-2. Si lo haces, Freezer gana inmediatamente 1 ficha de Ataque apuntado, 1 ficha de Esquiva y prepara todas sus cartas de mejora agotadas y armas con la cualidad Agostar L.',
    },
    {
      id: 'ME24',
      nombre: 'Protocolos de Combate Mejorados',
      tipo: 'Mando',
      coste: 10,
      restriccion: 'Solo Dr. Gero (Androide 20)',
      descripcion:
        'Acción de carta (I). Elige una unidad "Androide" aliada a alcance 1-3. Hasta el final de la ronda, esa unidad gana una de las siguientes cualidades a tu elección: Acometida o Tirador de primera 1.',
    },
    {
      id: 'ME25',
      nombre: 'Aumento de Poder',
      tipo: 'Fuerza',
      coste: 10,
      restriccion: 'Ninguna',
      descripcion:
        'Agotar (L). Acción de carta (I). Hasta el final de tu activación, tus armas ganan Impacto 1.',
    },
    {
      id: 'ME26',
      nombre: 'Barrera de Ki',
      tipo: 'Fuerza',
      coste: 12,
      restriccion: 'Ninguna',
      descripcion:
        'Agotar (L). Cuando te defiendas, después del paso "Modificar los dados de ataque", puedes agotar esta carta para cancelar 1 resultado de impacto (A).',
    },
    {
      id: 'ME27',
      nombre: 'Onda de Ki',
      tipo: 'Fuerza',
      coste: 8,
      restriccion: 'Ninguna',
      descripcion:
        'Acción de carta (I). Elige una unidad de infantería enemiga a alcance 1. Esa unidad debe realizar un movimiento de Velocidad 1 directamente en dirección opuesta a ti. Este movimiento no provoca ataques de unidades trabadas y no puede terminar en contacto peana con peana con otra miniatura o sobre terreno infranqueable.',
    },
    {
      id: 'ME28',
      nombre: 'Carga de Ki',
      tipo: 'Fuerza',
      coste: 5,
      restriccion: 'Ninguna',
      descripcion:
        'Acción de carta (I): Coloca 1 ficha de Energía sobre esta carta (máximo 3). Cuando ataques, antes de reunir tu reserva de ataque, puedes retirar cualquier número de fichas de Energía. Por cada ficha retirada, elige uno de los siguientes beneficios (puedes elegir el mismo varias veces):\n• Añade 1 dado de ataque negro a tu reserva de ataque.\n• Tu reserva de ataque gana Perforante 1.',
    },
    {
      id: 'ME29',
      nombre: 'Kaioken x10',
      tipo: 'Fuerza',
      coste: 18,
      restriccion: 'Solo Goku',
      descripcion:
        'Agotar (L). Acción de carta (I). Sufre 1 herida. Hasta el final de tu activación, tus armas ganan Perforante 2 e Impacto 2.',
    },
    {
      id: 'ME30',
      nombre: 'Granada Infernal',
      tipo: 'Fuerza',
      coste: 18,
      restriccion: 'Solo Piccolo',
      descripcion:
        'Acción de carta (II). Realiza un ataque especial contra una unidad enemiga a alcance 1-3 usando 4 dados negros. Este ataque tiene las cualidades Deflagración e Inmovilización 2.',
    },
    {
      id: 'ME31',
      nombre: 'Final Crash',
      tipo: 'Fuerza',
      coste: 16,
      restriccion: 'Solo Vegeta',
      descripcion:
        'Acción de carta (II). Ganas la siguiente arma para esta activación:\n• Nombre: Final Crash\n• Alcance: 1-4\n• Dados: 4 rojos\n• Cualidades: Perforante 1, Impacto 1, Agostar L, Impacto Arrasador.',
    },
    {
      id: 'ME32',
      nombre: 'Disco Destructor',
      tipo: 'Fuerza',
      coste: 15,
      restriccion: 'Solo Freezer',
      descripcion:
        'Acción de carta (II). Realiza un ataque especial a alcance 1-3 usando 3 dados rojos. El ataque tiene las cualidades Perforante 2 e Impacto 1.',
    },
    {
      id: 'ME33',
      nombre: 'Cañón Lácteo',
      tipo: 'Fuerza',
      coste: 12,
      restriccion: 'Solo Capitán Ginyu',
      descripcion:
        'Acción de carta (I). Realiza un ataque especial a alcance 1-2 usando 1 dado rojo y 2 negros. El ataque tiene las cualidades Impacto 1 e Inmovilización 1.',
    },
    {
      id: 'ME34',
      nombre: 'Núcleo de Poder Sobrecalentado',
      tipo: 'Fuerza',
      coste: 12,
      restriccion: 'Solo Androide 16',
      descripcion:
        "Agotar (L). Cuando realices un ataque con tu arma Hell's Flash, después de que el ataque se resuelva, puedes agotar esta carta para ganar 1 ficha de Ataque apuntado. Esta ficha no se retira durante la fase Final de la ronda.",
    },
    {
      id: 'ME35',
      nombre: 'Destello Solar Cegador',
      tipo: 'Fuerza',
      coste: 12,
      restriccion: 'Solo Cell',
      descripcion:
        'Ganas la siguiente acción:\n• ¡Taiyoken! (Acción de carta I): Elige una unidad enemiga a alcance 1 y en línea de visión. Esa unidad gana 2 fichas de Inmovilización.',
    },
    {
      id: 'ME36',
      nombre: 'Rayo Mortal Perfecto',
      tipo: 'Fuerza',
      coste: 16,
      restriccion: 'Solo Cell',
      descripcion:
        'Acción de carta (II). Realiza un ataque especial a alcance 1-3 usando 3 dados rojos. Este ataque tiene la cualidad Perforante 2.',
    },
    {
      id: 'ME37',
      nombre: 'Potencial Saiyan Oculto',
      tipo: 'Cualidad',
      coste: 15,
      restriccion: 'Solo unidades con la cualidad Cola',
      descripcion:
        'Esta mejora no ocupa una ranura de mejora. Acción de carta (II). Retira tu miniatura del campo de batalla. Luego, coloca una miniatura de la unidad Ōzaru en la misma posición. Al final de la ronda en la que se usó esta habilidad, descarta esta carta de mejora.',
    },
  ];

  getFactions(): string[] {
    return [...new Set(this.UNIDADES_DB.map((u) => u.faccion))];
  }
}
